// Tool registry — all tool definitions for the /tools hub
// This is a separate file so page.tsx can only export the default component.

export interface ToolDef {
  id: string;
  label: string;
  description: string;
  href: string;
  tags: ToolTag[];
  icon: string; // Lucide icon name or shorthand
  status: 'live' | 'beta' | 'soon';
  clientOnly?: boolean;
  isNew?: boolean;
}

export type ToolTag =
  | 'image' | 'design' | 'dev' | 'audio' | 'crypto' | 'text' 
  | 'security' | 'network' | 'utility' | 'ai' | 'seo';

export const TAG_LABELS: Record<ToolTag, string> = {
  image:    'Imaging',
  design:   'Design',
  dev:      'Engineering',
  audio:    'Media',
  crypto:   'Web3',
  text:     'Content',
  security: 'Security',
  network:  'Network',
  utility:  'Productivity',
  ai:       'AI / ML',
  seo:      'SEO',
};

export const TOOLS: ToolDef[] = [
  // ── SPOTLIGHT (YouTube) ────────────────────────────────────────────────
  {
    id: 'yt-downloader',
    label: 'YouTube Pro Downloader',
    description: 'High-fidelity extraction of MP4 video and MP3/WAV/M4A audio. Direct from source.',
    href: '/tools/yt-downloader',
    icon: 'Youtube',
    tags: ['audio', 'utility'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'screen-recorder',
    label: 'Screen Recorder',
    description: 'Capture screen, window, or tab with system/mic audio. No install required. Export WebM.',
    href: '/tools/screen-recorder',
    icon: 'Monitor',
    tags: ['utility', 'video'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'audio-trimmer',
    label: 'Audio Trimmer',
    description: 'Visually trim and cut audio files. Waveform editor with precision controls. Client-side WAV export.',
    href: '/tools/audio-trimmer',
    icon: 'Scissors',
    tags: ['audio'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  // ── IMAGING ─────────────────────────────────────────────────────────────
  {
    id: 'background-remover',
    label: 'Background Remover',
    description: 'Neural background isolation. 100% browser-side processing.',
    href: '/tools/background-remover',
    tags: ['image', 'ai'],
    icon: 'Layers',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'image-converter',
    label: 'Batch Image Converter',
    description: 'Universal format conversion: PNG, JPG, WebP, AVIF. Supports bulk processing.',
    href: '/tools/image-converter',
    tags: ['image'],
    icon: 'RefreshCw',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'image-compress',
    label: 'Image Optimizer',
    description: 'Lossy and lossless compression with real-time visual quality balancing.',
    href: '/tools/image-compress',
    tags: ['image'],
    icon: 'Zap',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'upscale',
    label: 'AI Upscaler (4×)',
    description: 'Enhance resolution and recover detail using Real-ESRGAN models.',
    href: '/tools/upscale',
    tags: ['image', 'ai'],
    icon: 'Maximize',
    status: 'live',
  },
  {
    id: 'vectorize',
    label: 'Raster to SVG',
    description: 'Convert bitmap images into scalable vector graphics via edge-detection AI.',
    href: '/tools/vectorize',
    tags: ['image', 'ai'],
    icon: 'PenTool',
    status: 'live',
  },
  // ── DESIGN ──────────────────────────────────────────────────────────────
  {
    id: 'css-generator',
    label: 'CSS Generator Suite',
    description: 'Professional-grade builders for gradients, glassmorphism, and complex shadows.',
    href: '/tools/css-generator',
    tags: ['design', 'dev'],
    icon: 'Code',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'color-tools',
    label: 'Color Architect',
    description: 'WCAG contrast analysis, harmony generation, and multi-format conversion.',
    href: '/tools/color-tools',
    tags: ['design'],
    icon: 'Palette',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'type-scale',
    label: 'Typography Scaler',
    description: 'Generate mathematically consistent type systems. Export as CSS variables.',
    href: '/tools/type-scale',
    tags: ['design', 'dev'],
    icon: 'Type',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'mockup',
    label: 'Device Mockups',
    description: 'Immersive hardware frames for MacBook, iPhone, and modern browsers.',
    href: '/tools/mockup',
    tags: ['design'],
    icon: 'Monitor',
    status: 'live',
    clientOnly: true,
  },
  // ── ENGINEERING ─────────────────────────────────────────────────────────
  {
    id: 'json-tools',
    label: 'JSON Intelligence',
    description: 'Advanced formatting, schema generation, and TypeScript interface mapping.',
    href: '/tools/json-tools',
    tags: ['dev'],
    icon: 'FileJson',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'regex-tester',
    label: 'Regex Pro Tester',
    description: 'Live regular expression debugger with group captures and pattern library.',
    href: '/tools/regex-tester',
    tags: ['dev'],
    icon: 'Search',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'curl-builder',
    label: 'cURL Architect',
    description: 'Visually construct complex API requests with headers, auth, and payloads.',
    href: '/tools/curl-builder',
    tags: ['dev', 'network'],
    icon: 'Globe',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'docker-gen',
    label: 'Docker Configuration',
    description: 'Interactive run command builder with volume and network mapping.',
    href: '/tools/docker-gen',
    tags: ['dev'],
    icon: 'Box',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'svg-to-jsx',
    label: 'SVG to JSX Architect',
    description: 'Synthesize optimized React components from raw vector markup. CamelCase mapping included.',
    href: '/tools/svg-to-jsx',
    tags: ['dev', 'design'],
    icon: 'FileCode',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'wifi-qr',
    label: 'WiFi QR Configurator',
    description: 'Generate high-fidelity QR codes for seamless wireless network onboarding.',
    href: '/tools/wifi-qr',
    tags: ['utility', 'network'],
    icon: 'Wifi',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  // ── SECURITY ────────────────────────────────────────────────────────────
  {
    id: 'aes-tool',
    label: 'AES Encryption',
    description: 'Military-grade 256-bit GCM encryption and decryption. Client-side only.',
    href: '/tools/aes-tool',
    tags: ['security', 'crypto'],
    icon: 'Lock',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'pw-strength',
    label: 'Password Auditor',
    description: 'Entropy-based strength analysis and brute-force time estimation.',
    href: '/tools/pw-strength',
    tags: ['security'],
    icon: 'ShieldCheck',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'jwt-debugger',
    label: 'JWT Inspector',
    description: 'Decode and validate JSON Web Tokens. Inspect claims and signatures.',
    href: '/tools/jwt-debugger',
    tags: ['security', 'dev'],
    icon: 'Key',
    status: 'live',
    clientOnly: true,
  },
  // ── CONTENT ─────────────────────────────────────────────────────────────
  {
    id: 'markdown',
    label: 'Markdown Editor',
    description: 'Split-pane GFM editor with synchronized rendering and HTML export.',
    href: '/tools/markdown',
    tags: ['text', 'dev'],
    icon: 'FileText',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'link-scraper',
    label: 'Intelligence Scraper',
    description: 'Extract structured links, images, and metadata from any public URL.',
    href: '/tools/link-scraper',
    tags: ['dev', 'seo'],
    icon: 'Activity',
    status: 'live',
  },
  {
    id: 'og-preview',
    label: 'Social Graph Preview',
    description: 'Real-time simulation of link appearances on X, Facebook, and Discord.',
    href: '/tools/og-preview',
    tags: ['design', 'seo'],
    icon: 'Share2',
    status: 'live',
    clientOnly: true,
  },
  // ── PRODUCTIVITY ────────────────────────────────────────────────────────
  {
    id: 'whiteboard',
    label: 'Infinite Whiteboard',
    description: 'High-performance collaborative canvas for system design and ideation.',
    href: '/tools/whiteboard',
    tags: ['utility'],
    icon: 'Edit3',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'pomodoro',
    label: 'Focus Protocol',
    description: 'Advanced productivity timer with session tracking and break management.',
    href: '/tools/pomodoro',
    tags: ['utility'],
    icon: 'Clock',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'snippets',
    label: 'Snippet Library',
    description: 'Persistent local storage for high-frequency code blocks.',
    href: '/tools/snippets',
    tags: ['dev', 'utility'],
    icon: 'Save',
    status: 'live',
  },
];
