// Tool registry — all tool definitions for the /tools hub
// This is a separate file so page.tsx can only export the default component.

export interface ToolDef {
  id: string;
  label: string;
  description: string;
  href: string;
  tags: ToolTag[];
  icon: string;
  status: 'live' | 'beta' | 'soon';
  clientOnly?: boolean;
  isNew?: boolean;
}

export type ToolTag =
  | 'image' | 'design' | 'dev' | 'gamedev' | 'pdf'
  | 'text' | 'crypto' | 'audio' | 'collab' | 'misc';

export const TAG_LABELS: Record<ToolTag, string> = {
  image:   'Image',
  design:  'Design',
  dev:     'Dev',
  gamedev: 'Game Dev',
  pdf:     'PDF',
  text:    'Text',
  crypto:  '₿ Crypto',
  audio:   'Audio',
  collab:  'Collab',
  misc:    'Misc',
};

export const TOOLS: ToolDef[] = [
  // ── IMAGE ────────────────────────────────────────────────────────────────
  {
    id: 'background-remover',
    label: 'Background Remover',
    description: 'Remove backgrounds from images instantly. Runs entirely in your browser — no upload required.',
    href: '/tools/background-remover',
    tags: ['image'],
    icon: '✂️',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'image-converter',
    label: 'Image Converter',
    description: 'Convert between PNG, JPG, WebP, GIF, and AVIF. Batch up to 10 files at once.',
    href: '/tools/image-converter',
    tags: ['image'],
    icon: '🔄',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'image-compress',
    label: 'Image Compressor',
    description: 'Compress images with a quality slider. Live before/after size comparison.',
    href: '/tools/image-compress',
    tags: ['image'],
    icon: '🗜️',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'image-resize',
    label: 'Image Resizer',
    description: 'Resize and crop images. Social media presets for every platform. Batch mode.',
    href: '/tools/image-resize',
    tags: ['image'],
    icon: '📐',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'color-palette',
    label: 'Color Palette Extractor',
    description: 'Extract dominant colors from any image. Export as CSS variables, JSON, or Tailwind config.',
    href: '/tools/color-palette',
    tags: ['image', 'design'],
    icon: '🎨',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'social-resize',
    label: 'Social Media Resizer',
    description: 'Upload once, export for every platform: Instagram, Twitter, YouTube, TikTok, LinkedIn, OG.',
    href: '/tools/social-resize',
    tags: ['image'],
    icon: '📱',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'sprite-packer',
    label: 'Sprite Sheet Packer',
    description: 'Pack multiple PNGs into a sprite atlas. Exports PNG + JSON manifest with texture coordinates.',
    href: '/tools/sprite-packer',
    tags: ['image', 'gamedev'],
    icon: '🗃️',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'pixel-editor',
    label: 'Pixel Art Editor',
    description: 'Quick browser-based pixel art editor. Grid canvas, pencil, fill, eraser, palette. Export PNG.',
    href: '/tools/pixel-editor',
    tags: ['image', 'gamedev'],
    icon: '🕹️',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'favicon',
    label: 'Favicon Generator',
    description: 'Upload any image → favicon.ico (16/32/48/64px), PNG variants, apple-touch-icon. ZIP download.',
    href: '/tools/favicon',
    tags: ['image', 'dev'],
    icon: '🌟',
    status: 'live',
    clientOnly: true,
  },
  // ── DESIGN ───────────────────────────────────────────────────────────────
  {
    id: 'css-generator',
    label: 'CSS Generator Suite',
    description: 'Gradient, glassmorphism, box shadow, border radius, and animation builders with live preview.',
    href: '/tools/css-generator',
    tags: ['design', 'dev'],
    icon: '🎨',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'color-tools',
    label: 'Color Utilities',
    description: 'Hex/RGB/HSL/OKLCH converter, WCAG contrast checker, color harmonies, and palette generator.',
    href: '/tools/color-tools',
    tags: ['design', 'dev'],
    icon: '🌈',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'og-preview',
    label: 'Open Graph Preview',
    description: 'Preview how your link appears on Twitter/X, Facebook, LinkedIn, Discord, and Slack.',
    href: '/tools/og-preview',
    tags: ['design', 'dev'],
    icon: '🔗',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'mockup',
    label: 'Mockup Generator',
    description: 'Drop your screenshot into device frames: MacBook, iPhone, iPad, Android, Browser window.',
    href: '/tools/mockup',
    tags: ['design'],
    icon: '🖼️',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'font-pairer',
    label: 'Font Pairer',
    description: 'Browse Google Fonts, pick heading + body pairs. Live preview with your own text.',
    href: '/tools/font-pairer',
    tags: ['design'],
    icon: '✍️',
    status: 'live',
    clientOnly: true,
  },
  // ── DEV ──────────────────────────────────────────────────────────────────
  {
    id: 'json-tools',
    label: 'JSON Toolkit',
    description: 'Format, validate, minify, diff, and convert JSON. JSON path queries. All client-side.',
    href: '/tools/json-tools',
    tags: ['dev'],
    icon: '{ }',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'regex',
    label: 'Regex Tester',
    description: 'Live match highlighting, group captures, pattern explanation, and a library of common patterns.',
    href: '/tools/regex',
    tags: ['dev'],
    icon: '🔍',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'encode-decode',
    label: 'Encode / Decode',
    description: 'Base64, URL encoding, HTML entities, Unicode escape, JWT decoder, Morse code, ROT13.',
    href: '/tools/encode-decode',
    tags: ['dev'],
    icon: '🔐',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'hash',
    label: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512, SHA-3 for text or files. File checksum verifier.',
    href: '/tools/hash',
    tags: ['dev'],
    icon: '#️⃣',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'generators',
    label: 'Developer Generators',
    description: 'UUID v4/v7, password generator with entropy meter, Lorem ipsum, CRON builder, timestamp converter, text diff.',
    href: '/tools/generators',
    tags: ['dev'],
    icon: '⚡',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'markdown',
    label: 'Markdown Editor',
    description: 'Split-pane editor with live preview, GFM support, table of contents, and export to HTML.',
    href: '/tools/markdown',
    tags: ['dev', 'text'],
    icon: '📝',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'csv-tools',
    label: 'CSV / Data Tools',
    description: 'Convert CSV ↔ JSON ↔ YAML. Table viewer with sort and filter. Column statistics.',
    href: '/tools/csv-tools',
    tags: ['dev'],
    icon: '📊',
    status: 'live',
    clientOnly: true,
  },
  // ── GAME DEV ─────────────────────────────────────────────────────────────
  {
    id: 'tilemap',
    label: 'Tilemap Generator',
    description: 'Upload a tileset, paint tiles on a grid, export Tiled-compatible JSON. Game dev essential.',
    href: '/tools/tilemap',
    tags: ['gamedev'],
    icon: '🗺️',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'asset-manifest',
    label: 'Asset Manifest Builder',
    description: 'Drop a folder of assets, get a Phaser/Pixi/Unity-compatible manifest JSON instantly.',
    href: '/tools/asset-manifest',
    tags: ['gamedev', 'dev'],
    icon: '📋',
    status: 'live',
    clientOnly: true,
  },
  // ── PDF ──────────────────────────────────────────────────────────────────
  {
    id: 'pdf',
    label: 'PDF Toolkit',
    description: 'Merge PDFs, extract pages, convert to images, add watermarks, compress. All browser-side.',
    href: '/tools/pdf',
    tags: ['pdf'],
    icon: '📄',
    status: 'live',
    clientOnly: true,
  },
  // ── TEXT ─────────────────────────────────────────────────────────────────
  {
    id: 'text-tools',
    label: 'Text Utilities',
    description: 'Word counter, 7 case formats, slug generator, sort/dedup lines, extract URLs and emails.',
    href: '/tools/text-tools',
    tags: ['text'],
    icon: '📃',
    status: 'live',
    clientOnly: true,
  },
  // ── CRYPTO ───────────────────────────────────────────────────────────────
  {
    id: 'crypto-tools',
    label: 'Crypto / Web3 Utils',
    description: 'QR code generator, wallet address validator (BTC/ETH/SOL), ENS lookup, hex/dec/bin converter.',
    href: '/tools/crypto-tools',
    tags: ['crypto'],
    icon: '₿',
    status: 'live',
    clientOnly: true,
  },
  // ── AUDIO ────────────────────────────────────────────────────────────────
  {
    id: 'audio-tools',
    label: 'Audio Utilities',
    description: 'Visualize audio waveforms, view file metadata, and create animated GIFs from image sequences.',
    href: '/tools/audio-tools',
    tags: ['audio'],
    icon: '🎵',
    status: 'live',
    clientOnly: true,
  },
  // ── COLLAB ───────────────────────────────────────────────────────────────
  {
    id: 'whiteboard',
    label: 'Infinite Whiteboard',
    description: 'Open-source infinite canvas (tldraw). Shapes, arrows, sticky notes, freehand. Auto-saves locally.',
    href: '/tools/whiteboard',
    tags: ['collab'],
    icon: '✏️',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'snippets',
    label: 'Code Snippet Manager',
    description: 'Save, tag, and search code snippets. Syntax highlighting for 50+ languages. Public or private.',
    href: '/tools/snippets',
    tags: ['dev', 'collab'],
    icon: '💾',
    status: 'live',
    clientOnly: false,
  },
  // ── NEW TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'color-extractor',
    label: 'Color Extractor',
    description: 'Extract a color palette from any image. Runs k-means clustering client-side — no upload.',
    href: '/tools/color-extractor',
    tags: ['image', 'design'],
    icon: '🖌️',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'type-scale',
    label: 'Type Scale',
    description: 'Generate a visual typography scale from a base size and ratio. Export as CSS variables.',
    href: '/tools/type-scale',
    tags: ['design', 'dev'],
    icon: '🔤',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'gradient-generator',
    label: 'Gradient Generator',
    description: 'Build CSS gradients (linear, radial, conic) with live preview. Adjust stops and copy CSS.',
    href: '/tools/gradient-generator',
    tags: ['design', 'dev'],
    icon: '🌊',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'border-radius',
    label: 'Border Radius Visualizer',
    description: 'Interactive border-radius builder with per-corner sliders. Live preview and copy CSS.',
    href: '/tools/border-radius',
    tags: ['design', 'dev'],
    icon: '⬜',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'image-diff',
    label: 'Image Diff',
    description: 'Compare two images side-by-side with an interactive drag slider. Great for before/after.',
    href: '/tools/image-diff',
    tags: ['image', 'design'],
    icon: '🔀',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'readme-generator',
    label: 'README Generator',
    description: 'Fill in project details and generate a professional README.md instantly.',
    href: '/tools/readme-generator',
    tags: ['dev'],
    icon: '📖',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'jwt-debugger',
    label: 'JWT Debugger',
    description: 'Decode and inspect JWT tokens. View header, payload, and expiry. Entirely client-side.',
    href: '/tools/jwt-debugger',
    tags: ['dev', 'crypto'],
    icon: '🔑',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'base-converter',
    label: 'Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hexadecimal.',
    href: '/tools/base-converter',
    tags: ['dev'],
    icon: '🔢',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'tech-badges',
    label: 'Tech Stack Badge Builder',
    description: 'Select technologies and generate shields.io badge markdown for your README.',
    href: '/tools/tech-badges',
    tags: ['dev'],
    icon: '🏷️',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'media-downloader',
    label: 'Media Downloader',
    description: 'Download images, audio, and video from any public URL. Supports direct file links and HTML pages.',
    href: '/tools/media-downloader',
    icon: '⬇️',
    tags: ['image', 'audio', 'dev'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'link-scraper',
    label: 'Link Scraper',
    description: 'Extract all links, images, and metadata from any public webpage. Export as JSON or copy to clipboard.',
    href: '/tools/link-scraper',
    icon: '🕷️',
    tags: ['dev'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'diff',
    label: 'Text Diff',
    description: 'Compare two texts side by side. Lines added, removed, and unchanged are highlighted.',
    href: '/tools/diff',
    icon: '↔️',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'cron-builder',
    label: 'Cron Builder',
    description: 'Build and validate cron expressions. Human-readable description and next 5 run dates.',
    href: '/tools/cron-builder',
    icon: '⏰',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'sql-formatter',
    label: 'SQL Formatter',
    description: 'Format and prettify SQL queries. Keyword capitalization and proper indentation.',
    href: '/tools/sql-formatter',
    icon: '🗄️',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'color-converter',
    label: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and HSV with a live preview swatch.',
    href: '/tools/color-converter',
    icon: '🔵',
    tags: ['design', 'dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'password-generator',
    label: 'Password Generator',
    description: 'Generate strong passwords with length slider and character set options. Uses crypto.getRandomValues().',
    href: '/tools/password-generator',
    icon: '🔒',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  // ── BUSINESS / CONTENT ───────────────────────────────────────────────────
  {
    id: 'invoice',
    label: 'Invoice Generator',
    description: 'Create professional invoices with line items, tax selector, and one-click PDF print. No account required.',
    href: '/tools/invoice',
    icon: '🧾',
    tags: ['misc'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'privacy-policy',
    label: 'Privacy Policy Generator',
    description: 'Generate a privacy policy for your website. Pick data types, jurisdiction, and export as .txt.',
    href: '/tools/privacy-policy',
    icon: '🛡️',
    tags: ['misc', 'dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'md-to-html',
    label: 'Markdown to HTML',
    description: 'Paste Markdown and get a live preview plus the raw HTML output. Client-side parser, no upload.',
    href: '/tools/md-to-html',
    icon: '🌐',
    tags: ['dev', 'text'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'changelog-writer',
    label: 'Changelog Writer',
    description: 'Paste git log or bullet points and get a formatted CHANGELOG.md entry with categorised sections.',
    href: '/tools/changelog-writer',
    icon: '📝',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'json-to-types',
    label: 'JSON to TypeScript Types',
    description: 'Paste JSON and instantly get TypeScript interface definitions. Handles nesting, arrays, and nulls.',
    href: '/tools/json-to-types',
    icon: '🔷',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  // ── BATCH C ──────────────────────────────────────────────────────────────
  {
    id: 'shadow',
    label: 'CSS Shadow Generator',
    description: 'Build box-shadow and text-shadow with visual sliders. Multiple layers, color picker, copy CSS.',
    href: '/tools/shadow',
    icon: '🌑',
    tags: ['design', 'dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'aspect-ratio',
    label: 'Aspect Ratio Calculator',
    description: 'Calculate dimensions for any aspect ratio. Standard presets, social media sizes, and visual preview.',
    href: '/tools/aspect-ratio',
    icon: '📺',
    tags: ['design'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'font-weight',
    label: 'Font Weight Tester',
    description: 'Preview any Google Font in all weights 100–900. Load and copy the CSS font-weight declaration.',
    href: '/tools/font-weight',
    icon: '🅰️',
    tags: ['design'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'gradient-animator',
    label: 'Gradient Animator',
    description: 'Animate CSS gradients with @keyframes. Color stops, angle control, speed slider, copy CSS.',
    href: '/tools/gradient-animator',
    icon: '✨',
    tags: ['design', 'dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'icon-search',
    label: 'Icon Search',
    description: 'Search and copy Lucide icons as SVG, React JSX, or name. Filter by category. Pure client-side.',
    href: '/tools/icon-search',
    icon: '🔍',
    tags: ['design', 'dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  // ── DEV / UTILITY ────────────────────────────────────────────────────────
  {
    id: 'regex-tester',
    label: 'Regex Tester',
    description: 'Test regular expressions against text. See all matches highlighted.',
    href: '/tools/regex-tester',
    icon: '🔎',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'timestamp',
    label: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and back.',
    href: '/tools/timestamp',
    icon: '🕐',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'word-counter',
    label: 'Word Counter',
    description: 'Count words, characters, sentences, and estimate reading time.',
    href: '/tools/word-counter',
    icon: '🔢',
    tags: ['text'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'http-status',
    label: 'HTTP Status Codes',
    description: 'Searchable reference for all HTTP status codes.',
    href: '/tools/http-status',
    icon: '📡',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'markdown-preview',
    label: 'Markdown Previewer',
    description: 'Write Markdown and see a live preview instantly.',
    href: '/tools/markdown-preview',
    icon: '👁️',
    tags: ['text', 'dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'text-to-3d',
    label: 'Text to 3D',
    description: 'Generate 3D models from text using Meshy AI. Export GLB, FBX, OBJ for Unity, Unreal, or Blender.',
    href: '/tools/text-to-3d',
    icon: '🧊',
    tags: ['image', 'gamedev'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'skybox',
    label: 'Skybox Generator',
    description: 'Generate immersive 360° panoramic environments for games and VR using Blockade Labs Skybox AI.',
    href: '/tools/skybox',
    icon: '🌌',
    tags: ['image', 'gamedev'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'transcribe',
    label: 'Audio Transcription',
    description: 'Transcribe audio with speaker diarization, entity detection, and sentiment analysis via AssemblyAI Universal-2.',
    href: '/tools/transcribe',
    icon: '🎤',
    tags: ['audio'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'vectorize',
    label: 'Raster to SVG',
    description: 'Convert PNG/JPG/GIF images to clean scalable SVG vectors using Vectorizer.AI.',
    href: '/tools/vectorize',
    icon: '🖊️',
    tags: ['image'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'ideogram',
    label: 'Ideogram — Text in Images',
    description: 'Generate AI images where text actually renders correctly. Posters, logos, banners. Powered by Ideogram V2.',
    href: '/tools/ideogram',
    icon: '🖼️',
    tags: ['image'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'recraft',
    label: 'Recraft v3',
    description: 'Generate brand-quality illustrations, icons, and vector-style images with Recraft v3.',
    href: '/tools/recraft',
    icon: '🎭',
    tags: ['image', 'design'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'exa-search',
    label: 'Exa Semantic Search',
    description: 'Neural web search that finds content by meaning. Better than keyword search for research.',
    href: '/tools/exa-search',
    icon: '🔭',
    tags: ['dev', 'misc'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'favicon-extractor',
    label: 'Favicon Extractor',
    description: 'Extract favicons and icon sets from images.',
    href: '/tools/favicon-extractor',
    tags: ['dev'],
    icon: '🌐',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'link-checker',
    label: 'Link Checker',
    description: 'Validate links on a webpage and report broken URLs.',
    href: '/tools/link-checker',
    tags: ['dev'],
    icon: '✅',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'og-analyzer',
    label: 'OG Analyzer',
    description: 'Analyze Open Graph meta tags and preview social card rendering.',
    href: '/tools/og-analyzer',
    tags: ['dev', 'design'],
    icon: '📊',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'uuid',
    label: 'UUID Generator',
    description: 'Generate UUID v4 and v7 identifiers for development.',
    href: '/tools/uuid',
    tags: ['dev'],
    icon: '🆔',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'website-palette',
    label: 'Website Palette',
    description: 'Extract colors from a website URL and generate a palette.',
    href: '/tools/website-palette',
    tags: ['design', 'dev'],
    icon: '🎨',
    status: 'live',
    clientOnly: true,
  },
  // ── AI Tools ──────────────────────────────────────────────────────────────
  {
    id: 'upscale',
    label: 'AI Upscaler (4×)',
    description: 'Sharpen and enlarge images up to 4× with Real-ESRGAN. Free, runs on Hugging Face.',
    href: '/tools/upscale',
    tags: ['image'],
    icon: '🔬',
    status: 'live',
    isNew: true,
  },
  {
    id: 'interrogate',
    label: 'Image Interrogator',
    description: 'Extract a detailed text prompt from any image using BLIP. Great for reverse-engineering styles.',
    href: '/tools/interrogate',
    tags: ['image'],
    icon: '🔭',
    status: 'live',
    isNew: true,
  },
  {
    id: 'prompt-lab',
    label: 'Prompt Lab',
    description: 'Enhance and expand prompts with AI. Groq → Cerebras → Gemini chain. Mode-specific tuning.',
    href: '/prompt-lab',
    tags: ['image', 'design'],
    icon: '✨',
    status: 'live',
    isNew: true,
  },
  {
    id: 'ai-music',
    label: 'Music Generator',
    description: 'Generate backing music and soundscapes with MusicGen (Meta). Loop-ready MP3 output.',
    href: '/tools/music',
    tags: ['audio'],
    icon: '🎵',
    status: 'live',
    isNew: true,
  },
  {
    id: 'sfx-browser',
    label: 'Sound FX Browser',
    description: 'Search and preview 500k+ CC0 sound effects from Freesound. Download instantly.',
    href: '/tools/sfx',
    tags: ['audio', 'gamedev'],
    icon: '🔊',
    status: 'live',
    isNew: true,
  },
  {
    id: 'asset-search',
    label: 'Asset Search',
    description: 'Search Pixabay for 5M+ CC0 images, illustrations, and videos. Commercial use allowed.',
    href: '/tools/assets',
    tags: ['image', 'design'],
    icon: '🖼️',
    status: 'live',
    isNew: true,
  },
  {
    id: 'palette-gen',
    label: 'Palette Generator',
    description: 'Generate harmonious color palettes with AI. Export CSS variables, Tailwind config, or JSON.',
    href: '/tools/palette',
    tags: ['design'],
    icon: '🎨',
    status: 'live',
    isNew: true,
  },
];
